# ACTION METADATA
# https://docs.github.com/actions/creating-actions/metadata-syntax-for-github-actions

---
name: jq-action
author: '@flex-development'
description: A jq utility for GitHub Actions
inputs:
  data:
    description: the data to operate on
    required: true
  filter:
    description: |
      the filter to apply.
      the simplest filter is `.`, which copies jq's input to its output unmodified (except for formatting). for more advanced filters, see https://jqlang.github.io/jq/manual
    required: true
  options:
    description: |
      the options to apply to the filter.
      the raw output option, `-r`, will be prepended. with this option, if the result of the filter
      is a string, it will be written directly to standard output rather than being formatted as a
      JSON string with escapes and quotes
    required: false
outputs:
  result:
    description: the result of the filter
    value: ${{ steps.jq.outputs.result }}
runs:
  using: composite
  steps:
    - id: jq
      shell: bash
      run: |
        set -e

        # init command options.
        opts=-r

        # append options.
        [[ -n '${{ inputs.options }}' ]] && opts="$opts ${{ inputs.options }}"

        #  run command and set output.
        echo result=$(jq $opts ${{ inputs.filter }} ${{ inputs.data }}) >>$GITHUB_OUTPUT
branding:
  color: blue
  icon: search
